// lib/services/local_database.dart
// ════════════════════════════════════════════════════════════
// Hive Local Database — Offline-First Storage
// Stores: AppConfig, StudentProfile, Subjects, Topics, Quizzes
// Falls back to this data when internet is unavailable.
// ════════════════════════════════════════════════════════════

import 'package:hive_flutter/hive_flutter.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../models/app_config.dart';
import '../models/student_models.dart';

abstract final class HiveBoxes {
  static const appConfig  = 'app_config';
  static const profile    = 'profile';
  static const subjects   = 'subjects';
  static const topics     = 'topics';
  static const quizzes    = 'quizzes';
  static const badges     = 'badges';
  static const settings   = 'settings';
}

abstract final class HiveKeys {
  static const appConfig       = 'app_config_data';
  static const profile         = 'student_profile';
  static const isDarkTheme     = 'is_dark_theme';
  static const selectedLang    = 'selected_lang';
  static const stateCode       = 'state_code';
  static const hasOnboarded    = 'has_onboarded';
  static const hasConsented    = 'has_consented';
  static const wifiOnlySync    = 'wifi_only_sync';
  static const autoDownload    = 'auto_download';
  static const arSoundEnabled  = 'ar_sound';
  static const notifEnabled    = 'notif_enabled';
  static const dailyReminder   = 'daily_reminder';
}

class LocalDatabase {
  static bool _initialized = false;

  static Future<void> init() async {
    if (_initialized) return;
    await Hive.initFlutter();

    // Register adapters (generated by hive_generator)
    // Hive.registerAdapter(AppConfigAdapter());
    // Hive.registerAdapter(FeatureFlagsAdapter());
    // Hive.registerAdapter(BrandingConfigAdapter());
    // Hive.registerAdapter(NavItemAdapter());
    // Hive.registerAdapter(StudentProfileAdapter());
    // Hive.registerAdapter(SubjectAdapter());
    // Hive.registerAdapter(TopicAdapter());
    // Hive.registerAdapter(QuizAdapter());
    // Hive.registerAdapter(QuizQuestionAdapter());
    // Hive.registerAdapter(BadgeAdapter());

    await Future.wait([
      Hive.openBox<dynamic>(HiveBoxes.appConfig),
      Hive.openBox<dynamic>(HiveBoxes.profile),
      Hive.openBox<dynamic>(HiveBoxes.subjects),
      Hive.openBox<dynamic>(HiveBoxes.topics),
      Hive.openBox<dynamic>(HiveBoxes.quizzes),
      Hive.openBox<dynamic>(HiveBoxes.badges),
      Hive.openBox<dynamic>(HiveBoxes.settings),
    ]);

    _initialized = true;
  }

  // ── Settings ──────────────────────────────────────────────
  static Box<dynamic> get _settings => Hive.box(HiveBoxes.settings);

  static bool   get isDarkTheme    => _settings.get(HiveKeys.isDarkTheme,   defaultValue: true)  as bool;
  static String get selectedLang   => _settings.get(HiveKeys.selectedLang,  defaultValue: 'en')  as String;
  static String get stateCode      => _settings.get(HiveKeys.stateCode,     defaultValue: '')    as String;
  static bool   get hasOnboarded   => _settings.get(HiveKeys.hasOnboarded,  defaultValue: false) as bool;
  static bool   get hasConsented   => _settings.get(HiveKeys.hasConsented,  defaultValue: false) as bool;
  static bool   get wifiOnlySync   => _settings.get(HiveKeys.wifiOnlySync,  defaultValue: true)  as bool;
  static bool   get autoDownload   => _settings.get(HiveKeys.autoDownload,  defaultValue: true)  as bool;
  static bool   get arSoundEnabled => _settings.get(HiveKeys.arSoundEnabled,defaultValue: true)  as bool;
  static bool   get notifEnabled   => _settings.get(HiveKeys.notifEnabled,  defaultValue: true)  as bool;
  static bool   get dailyReminder  => _settings.get(HiveKeys.dailyReminder, defaultValue: true)  as bool;

  static Future<void> setDarkTheme(bool v)    => _settings.put(HiveKeys.isDarkTheme,    v);
  static Future<void> setLanguage(String v)    => _settings.put(HiveKeys.selectedLang,  v);
  static Future<void> setStateCode(String v)   => _settings.put(HiveKeys.stateCode,     v);
  static Future<void> setOnboarded(bool v)     => _settings.put(HiveKeys.hasOnboarded,  v);
  static Future<void> setConsented(bool v)     => _settings.put(HiveKeys.hasConsented,  v);
  static Future<void> setWifiOnly(bool v)      => _settings.put(HiveKeys.wifiOnlySync,  v);
  static Future<void> setAutoDownload(bool v)  => _settings.put(HiveKeys.autoDownload,  v);
  static Future<void> setArSound(bool v)       => _settings.put(HiveKeys.arSoundEnabled,v);
  static Future<void> setNotifications(bool v) => _settings.put(HiveKeys.notifEnabled,  v);
  static Future<void> setDailyReminder(bool v) => _settings.put(HiveKeys.dailyReminder, v);

  // ── AppConfig ─────────────────────────────────────────────
  static Future<void> saveAppConfig(Map<String, dynamic> json) =>
      Hive.box<dynamic>(HiveBoxes.appConfig).put(HiveKeys.appConfig, json);

  static Map<String, dynamic>? loadAppConfig() {
    final raw = Hive.box<dynamic>(HiveBoxes.appConfig).get(HiveKeys.appConfig);
    return raw != null ? Map<String, dynamic>.from(raw as Map) : null;
  }

  // ── Student Profile ───────────────────────────────────────
  static Future<void> saveProfile(Map<String, dynamic> json) =>
      Hive.box<dynamic>(HiveBoxes.profile).put(HiveKeys.profile, json);

  static Map<String, dynamic>? loadProfile() {
    final raw = Hive.box<dynamic>(HiveBoxes.profile).get(HiveKeys.profile);
    return raw != null ? Map<String, dynamic>.from(raw as Map) : null;
  }

  // ── Subjects ──────────────────────────────────────────────
  static Future<void> saveSubjects(List<Map<String, dynamic>> list) =>
      Hive.box<dynamic>(HiveBoxes.subjects).put('all', list);

  static List<Map<String, dynamic>> loadSubjects() {
    final raw = Hive.box<dynamic>(HiveBoxes.subjects).get('all');
    if (raw == null) return [];
    return (raw as List).map((e) => Map<String, dynamic>.from(e as Map)).toList();
  }

  // ── Topics ────────────────────────────────────────────────
  static Future<void> saveTopics(String subjectId, List<Map<String, dynamic>> list) =>
      Hive.box<dynamic>(HiveBoxes.topics).put(subjectId, list);

  static List<Map<String, dynamic>> loadTopics(String subjectId) {
    final raw = Hive.box<dynamic>(HiveBoxes.topics).get(subjectId);
    if (raw == null) return [];
    return (raw as List).map((e) => Map<String, dynamic>.from(e as Map)).toList();
  }

  static Future<void> clear() async {
    await Future.wait([
      Hive.box<dynamic>(HiveBoxes.profile).clear(),
      Hive.box<dynamic>(HiveBoxes.subjects).clear(),
      Hive.box<dynamic>(HiveBoxes.topics).clear(),
      Hive.box<dynamic>(HiveBoxes.quizzes).clear(),
    ]);
  }
}

// ── Settings Notifier (reactive) ──────────────────────────────
class SettingsState {
  final bool   isDark;
  final String language;
  final bool   wifiOnly;
  final bool   autoDownload;
  final bool   arSound;
  final bool   notifEnabled;

  const SettingsState({
    required this.isDark,
    required this.language,
    required this.wifiOnly,
    required this.autoDownload,
    required this.arSound,
    required this.notifEnabled,
  });

  SettingsState copyWith({
    bool?   isDark,
    String? language,
    bool?   wifiOnly,
    bool?   autoDownload,
    bool?   arSound,
    bool?   notifEnabled,
  }) => SettingsState(
    isDark:       isDark        ?? this.isDark,
    language:     language      ?? this.language,
    wifiOnly:     wifiOnly      ?? this.wifiOnly,
    autoDownload: autoDownload  ?? this.autoDownload,
    arSound:      arSound       ?? this.arSound,
    notifEnabled: notifEnabled  ?? this.notifEnabled,
  );
}

class SettingsNotifier extends Notifier<SettingsState> {
  @override
  SettingsState build() => SettingsState(
    isDark:       LocalDatabase.isDarkTheme,
    language:     LocalDatabase.selectedLang,
    wifiOnly:     LocalDatabase.wifiOnlySync,
    autoDownload: LocalDatabase.autoDownload,
    arSound:      LocalDatabase.arSoundEnabled,
    notifEnabled: LocalDatabase.notifEnabled,
  );

  Future<void> toggleDark()   async { await LocalDatabase.setDarkTheme(!state.isDark); state = state.copyWith(isDark: !state.isDark); }
  Future<void> setLang(String l) async { await LocalDatabase.setLanguage(l); state = state.copyWith(language: l); }
  Future<void> toggleWifi()   async { await LocalDatabase.setWifiOnly(!state.wifiOnly); state = state.copyWith(wifiOnly: !state.wifiOnly); }
  Future<void> toggleAutoDownload() async { await LocalDatabase.setAutoDownload(!state.autoDownload); state = state.copyWith(autoDownload: !state.autoDownload); }
  Future<void> toggleArSound() async { await LocalDatabase.setArSound(!state.arSound); state = state.copyWith(arSound: !state.arSound); }
  Future<void> toggleNotif()  async { await LocalDatabase.setNotifications(!state.notifEnabled); state = state.copyWith(notifEnabled: !state.notifEnabled); }
}

final settingsProvider = NotifierProvider<SettingsNotifier, SettingsState>(
  SettingsNotifier.new);
